volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:16.2-alpine3.19
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    command:
      -p 5432
    networks:
      - banner-network

  migrator:
    build:
      context: ../
      dockerfile: deployments/dockerfiles/migrator.Dockerfile
    env_file:
      - env/.env
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
    networks:
      - banner-network

networks:
  banner-network:
    driver: bridge