// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rotation.proto

package rotation_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddBannerRequest) Reset() {
	*x = AddBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerRequest) ProtoMessage() {}

func (x *AddBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerRequest.ProtoReflect.Descriptor instead.
func (*AddBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{0}
}

func (x *AddBannerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddBannerResponse) Reset() {
	*x = AddBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerResponse) ProtoMessage() {}

func (x *AddBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerResponse.ProtoReflect.Descriptor instead.
func (*AddBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{1}
}

func (x *AddBannerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBannerRequest) Reset() {
	*x = DeleteBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerRequest) ProtoMessage() {}

func (x *DeleteBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteBannerResponse) Reset() {
	*x = DeleteBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBannerResponse) ProtoMessage() {}

func (x *DeleteBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBannerResponse.ProtoReflect.Descriptor instead.
func (*DeleteBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBannerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddSlotRequest) Reset() {
	*x = AddSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSlotRequest) ProtoMessage() {}

func (x *AddSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSlotRequest.ProtoReflect.Descriptor instead.
func (*AddSlotRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{4}
}

func (x *AddSlotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddSlotResponse) Reset() {
	*x = AddSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSlotResponse) ProtoMessage() {}

func (x *AddSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSlotResponse.ProtoReflect.Descriptor instead.
func (*AddSlotResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{5}
}

func (x *AddSlotResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSlotRequest) Reset() {
	*x = DeleteSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotRequest) ProtoMessage() {}

func (x *DeleteSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSlotRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSlotRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteSlotResponse) Reset() {
	*x = DeleteSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSlotResponse) ProtoMessage() {}

func (x *DeleteSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSlotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSlotResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddSocialGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddSocialGroupRequest) Reset() {
	*x = AddSocialGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSocialGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSocialGroupRequest) ProtoMessage() {}

func (x *AddSocialGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSocialGroupRequest.ProtoReflect.Descriptor instead.
func (*AddSocialGroupRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{8}
}

func (x *AddSocialGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddSocialGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddSocialGroupResponse) Reset() {
	*x = AddSocialGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSocialGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSocialGroupResponse) ProtoMessage() {}

func (x *AddSocialGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSocialGroupResponse.ProtoReflect.Descriptor instead.
func (*AddSocialGroupResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{9}
}

func (x *AddSocialGroupResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSocialGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSocialGroupRequest) Reset() {
	*x = DeleteSocialGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSocialGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialGroupRequest) ProtoMessage() {}

func (x *DeleteSocialGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteSocialGroupRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSocialGroupRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSocialGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteSocialGroupResponse) Reset() {
	*x = DeleteSocialGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSocialGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSocialGroupResponse) ProtoMessage() {}

func (x *DeleteSocialGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSocialGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteSocialGroupResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSocialGroupResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AttachBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdBanner int32 `protobuf:"varint,1,opt,name=id_banner,json=idBanner,proto3" json:"id_banner,omitempty"`
	IdSlot   int32 `protobuf:"varint,2,opt,name=id_slot,json=idSlot,proto3" json:"id_slot,omitempty"`
}

func (x *AttachBannerRequest) Reset() {
	*x = AttachBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerRequest) ProtoMessage() {}

func (x *AttachBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerRequest.ProtoReflect.Descriptor instead.
func (*AttachBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{12}
}

func (x *AttachBannerRequest) GetIdBanner() int32 {
	if x != nil {
		return x.IdBanner
	}
	return 0
}

func (x *AttachBannerRequest) GetIdSlot() int32 {
	if x != nil {
		return x.IdSlot
	}
	return 0
}

type AttachBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AttachBannerResponse) Reset() {
	*x = AttachBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerResponse) ProtoMessage() {}

func (x *AttachBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerResponse.ProtoReflect.Descriptor instead.
func (*AttachBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{13}
}

func (x *AttachBannerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DetachBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdBanner int32 `protobuf:"varint,1,opt,name=id_banner,json=idBanner,proto3" json:"id_banner,omitempty"`
	IdSlot   int32 `protobuf:"varint,2,opt,name=id_slot,json=idSlot,proto3" json:"id_slot,omitempty"`
}

func (x *DetachBannerRequest) Reset() {
	*x = DetachBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerRequest) ProtoMessage() {}

func (x *DetachBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerRequest.ProtoReflect.Descriptor instead.
func (*DetachBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{14}
}

func (x *DetachBannerRequest) GetIdBanner() int32 {
	if x != nil {
		return x.IdBanner
	}
	return 0
}

func (x *DetachBannerRequest) GetIdSlot() int32 {
	if x != nil {
		return x.IdSlot
	}
	return 0
}

type DetachBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DetachBannerResponse) Reset() {
	*x = DetachBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerResponse) ProtoMessage() {}

func (x *DetachBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerResponse.ProtoReflect.Descriptor instead.
func (*DetachBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{15}
}

func (x *DetachBannerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HitBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdBanner      int32 `protobuf:"varint,1,opt,name=id_banner,json=idBanner,proto3" json:"id_banner,omitempty"`
	IdSlot        int32 `protobuf:"varint,2,opt,name=id_slot,json=idSlot,proto3" json:"id_slot,omitempty"`
	IdSocialGroup int32 `protobuf:"varint,3,opt,name=id_social_group,json=idSocialGroup,proto3" json:"id_social_group,omitempty"`
}

func (x *HitBannerRequest) Reset() {
	*x = HitBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HitBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitBannerRequest) ProtoMessage() {}

func (x *HitBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitBannerRequest.ProtoReflect.Descriptor instead.
func (*HitBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{16}
}

func (x *HitBannerRequest) GetIdBanner() int32 {
	if x != nil {
		return x.IdBanner
	}
	return 0
}

func (x *HitBannerRequest) GetIdSlot() int32 {
	if x != nil {
		return x.IdSlot
	}
	return 0
}

func (x *HitBannerRequest) GetIdSocialGroup() int32 {
	if x != nil {
		return x.IdSocialGroup
	}
	return 0
}

type HitBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HitBannerResponse) Reset() {
	*x = HitBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HitBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitBannerResponse) ProtoMessage() {}

func (x *HitBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitBannerResponse.ProtoReflect.Descriptor instead.
func (*HitBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{17}
}

func (x *HitBannerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SelectBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdSlot        int32 `protobuf:"varint,1,opt,name=id_slot,json=idSlot,proto3" json:"id_slot,omitempty"`
	IdSocialGroup int32 `protobuf:"varint,2,opt,name=id_social_group,json=idSocialGroup,proto3" json:"id_social_group,omitempty"`
}

func (x *SelectBannerRequest) Reset() {
	*x = SelectBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerRequest) ProtoMessage() {}

func (x *SelectBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerRequest.ProtoReflect.Descriptor instead.
func (*SelectBannerRequest) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{18}
}

func (x *SelectBannerRequest) GetIdSlot() int32 {
	if x != nil {
		return x.IdSlot
	}
	return 0
}

func (x *SelectBannerRequest) GetIdSocialGroup() int32 {
	if x != nil {
		return x.IdSocialGroup
	}
	return 0
}

type SelectBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdBanner int32 `protobuf:"varint,1,opt,name=id_banner,json=idBanner,proto3" json:"id_banner,omitempty"`
}

func (x *SelectBannerResponse) Reset() {
	*x = SelectBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerResponse) ProtoMessage() {}

func (x *SelectBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerResponse.ProtoReflect.Descriptor instead.
func (*SelectBannerResponse) Descriptor() ([]byte, []int) {
	return file_rotation_proto_rawDescGZIP(), []int{19}
}

func (x *SelectBannerResponse) GetIdBanner() int32 {
	if x != nil {
		return x.IdBanner
	}
	return 0
}

var File_rotation_proto protoreflect.FileDescriptor

var file_rotation_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x22, 0x34, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2e, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x32, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x21, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x39, 0x0a, 0x15, 0x41, 0x64, 0x64,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a,
	0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x19, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x4b, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x2e, 0x0a, 0x14,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x13,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x44, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x70, 0x0a, 0x10, 0x48, 0x69, 0x74,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64,
	0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x64, 0x53,
	0x6c, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x64, 0x5f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x64,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x2b, 0x0a, 0x11, 0x48,
	0x69, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x64, 0x5f, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x69, 0x64, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x22, 0x33, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x32, 0xca, 0x06, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x20,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1b,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x22, 0x2e, 0x72, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x25, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63,
	0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x09, 0x48, 0x69, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1d,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x48, 0x69, 0x74,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x48, 0x69, 0x74, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a,
	0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x2e,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x76, 0x61, 0x64, 0x73, 0x6b, 0x65, 0x76, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x2d, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x3b, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rotation_proto_rawDescOnce sync.Once
	file_rotation_proto_rawDescData = file_rotation_proto_rawDesc
)

func file_rotation_proto_rawDescGZIP() []byte {
	file_rotation_proto_rawDescOnce.Do(func() {
		file_rotation_proto_rawDescData = protoimpl.X.CompressGZIP(file_rotation_proto_rawDescData)
	})
	return file_rotation_proto_rawDescData
}

var file_rotation_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rotation_proto_goTypes = []any{
	(*AddBannerRequest)(nil),          // 0: rotation_v1.AddBannerRequest
	(*AddBannerResponse)(nil),         // 1: rotation_v1.AddBannerResponse
	(*DeleteBannerRequest)(nil),       // 2: rotation_v1.DeleteBannerRequest
	(*DeleteBannerResponse)(nil),      // 3: rotation_v1.DeleteBannerResponse
	(*AddSlotRequest)(nil),            // 4: rotation_v1.AddSlotRequest
	(*AddSlotResponse)(nil),           // 5: rotation_v1.AddSlotResponse
	(*DeleteSlotRequest)(nil),         // 6: rotation_v1.DeleteSlotRequest
	(*DeleteSlotResponse)(nil),        // 7: rotation_v1.DeleteSlotResponse
	(*AddSocialGroupRequest)(nil),     // 8: rotation_v1.AddSocialGroupRequest
	(*AddSocialGroupResponse)(nil),    // 9: rotation_v1.AddSocialGroupResponse
	(*DeleteSocialGroupRequest)(nil),  // 10: rotation_v1.DeleteSocialGroupRequest
	(*DeleteSocialGroupResponse)(nil), // 11: rotation_v1.DeleteSocialGroupResponse
	(*AttachBannerRequest)(nil),       // 12: rotation_v1.AttachBannerRequest
	(*AttachBannerResponse)(nil),      // 13: rotation_v1.AttachBannerResponse
	(*DetachBannerRequest)(nil),       // 14: rotation_v1.DetachBannerRequest
	(*DetachBannerResponse)(nil),      // 15: rotation_v1.DetachBannerResponse
	(*HitBannerRequest)(nil),          // 16: rotation_v1.HitBannerRequest
	(*HitBannerResponse)(nil),         // 17: rotation_v1.HitBannerResponse
	(*SelectBannerRequest)(nil),       // 18: rotation_v1.SelectBannerRequest
	(*SelectBannerResponse)(nil),      // 19: rotation_v1.SelectBannerResponse
}
var file_rotation_proto_depIdxs = []int32{
	0,  // 0: rotation_v1.Rotation.AddBanner:input_type -> rotation_v1.AddBannerRequest
	2,  // 1: rotation_v1.Rotation.DeleteBanner:input_type -> rotation_v1.DeleteBannerRequest
	4,  // 2: rotation_v1.Rotation.AddSlot:input_type -> rotation_v1.AddSlotRequest
	6,  // 3: rotation_v1.Rotation.DeleteSlot:input_type -> rotation_v1.DeleteSlotRequest
	8,  // 4: rotation_v1.Rotation.AddSocialGroup:input_type -> rotation_v1.AddSocialGroupRequest
	10, // 5: rotation_v1.Rotation.DeleteSocialGroup:input_type -> rotation_v1.DeleteSocialGroupRequest
	12, // 6: rotation_v1.Rotation.AttachBanner:input_type -> rotation_v1.AttachBannerRequest
	14, // 7: rotation_v1.Rotation.DetachBanner:input_type -> rotation_v1.DetachBannerRequest
	16, // 8: rotation_v1.Rotation.HitBanner:input_type -> rotation_v1.HitBannerRequest
	18, // 9: rotation_v1.Rotation.SelectBanner:input_type -> rotation_v1.SelectBannerRequest
	1,  // 10: rotation_v1.Rotation.AddBanner:output_type -> rotation_v1.AddBannerResponse
	3,  // 11: rotation_v1.Rotation.DeleteBanner:output_type -> rotation_v1.DeleteBannerResponse
	5,  // 12: rotation_v1.Rotation.AddSlot:output_type -> rotation_v1.AddSlotResponse
	7,  // 13: rotation_v1.Rotation.DeleteSlot:output_type -> rotation_v1.DeleteSlotResponse
	9,  // 14: rotation_v1.Rotation.AddSocialGroup:output_type -> rotation_v1.AddSocialGroupResponse
	11, // 15: rotation_v1.Rotation.DeleteSocialGroup:output_type -> rotation_v1.DeleteSocialGroupResponse
	13, // 16: rotation_v1.Rotation.AttachBanner:output_type -> rotation_v1.AttachBannerResponse
	15, // 17: rotation_v1.Rotation.DetachBanner:output_type -> rotation_v1.DetachBannerResponse
	17, // 18: rotation_v1.Rotation.HitBanner:output_type -> rotation_v1.HitBannerResponse
	19, // 19: rotation_v1.Rotation.SelectBanner:output_type -> rotation_v1.SelectBannerResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rotation_proto_init() }
func file_rotation_proto_init() {
	if File_rotation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rotation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AddSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AddSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AddSocialGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AddSocialGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSocialGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSocialGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AttachBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AttachBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DetachBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*DetachBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*HitBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*HitBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*SelectBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*SelectBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rotation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rotation_proto_goTypes,
		DependencyIndexes: file_rotation_proto_depIdxs,
		MessageInfos:      file_rotation_proto_msgTypes,
	}.Build()
	File_rotation_proto = out.File
	file_rotation_proto_rawDesc = nil
	file_rotation_proto_goTypes = nil
	file_rotation_proto_depIdxs = nil
}
